import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shane's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://github.com/ShanerCoder">Shane's Portfolio Page!</a>
        </h1>

        <p className={styles.description}>
          Get started by checking out the following projects:
        </p>

        <div className={styles.grid}>
          <a
            href="https://github.com/ShanerCoder/Snakes-And-Ladders-Clone"
            className={styles.card}
          >
            <h2>Snakes and Ladders &rarr;</h2>
            <p>
              Project created to develop a snakes and ladders clone primarially
              using PHP & Javascript.
            </p>
          </a>

          <a href="https://xtreme-tracking.vercel.app/" className={styles.card}>
            <h2>Xtreme Tracking &rarr;</h2>
            <p>
              Fitness Tracking Website with inbuilt social media functionality
              made using Next.Js.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ShanerCoder"
          target="_blank"
          rel="noopener noreferrer"
        >
          GitHub
          <span className={styles.logo}>
            <Image src="/GitHub.png" alt="GitHub Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
