import Head from "next/head";
import classes from "./HomePage.module.css";
import Image from "next/image";
import { useRouter } from "next/router";
import Card from "../Display/Card/Card";

function HomePage() {
  const router = useRouter();
  async function handleLoader(URL) {
    await router.push(URL);
  }

  return (
    <div className={classes.container}>
      <Head>
        <title>Shane's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome to{" "}
          <a className="linkLabel" href="https://github.com/ShanerCoder">
            Shane's Portfolio Page!{" "}
            <span className={classes.logo}>
              <Image
                src="/GitHub.png"
                alt="GitHub Logo"
                width={64}
                height={64}
              />
            </span>
          </a>
        </h1>

        <p className={classes.description}>
          Get started by checking out the following pages:
        </p>

        <div className={classes.grid}>
          <Card
            onClick={() => {
              handleLoader("/projects");
            }}
          >
            <h2>Projects&rarr;</h2>
            <p>A list of projects I have worked on in the past</p>
          </Card>

          <Card
            onClick={() => {
              handleLoader("/experience");
            }}
          >
            <h2>Experience&rarr;</h2>
            <p>A rundown of my professional experience</p>{" "}
          </Card>

          <Card
            onClick={() => {
              handleLoader("/other");
            }}
          >
            <h2>Other&rarr;</h2>
            <p>A list of for-fun projects created on this website</p>
          </Card>
        </div>
      </main>
    </div>
  );
}

export default HomePage;
