import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Image from "next/image";
import { useRouter } from "next/router";

function HomePage() {
  const router = useRouter();
  async function handleLoader(URL) {
    await router.push(URL);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Shane's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://github.com/ShanerCoder">
            Shane's Portfolio Page!{""}
            <span className={styles.logo}>
              <Image
                src="/GitHub.png"
                alt="GitHub Logo"
                width={64}
                height={64}
              />
            </span>
          </a>
        </h1>

        <p className={styles.description}>
          Get started by checking out the following pages:
        </p>

        <div className={styles.grid}>
          <div
            className={styles.card}
            onClick={() => {
              handleLoader("/projects");
            }}
          >
            <h2>Projects&rarr;</h2>
            <p>A list of projects I have worked on in the past</p>
          </div>

          <div
            className={styles.card}
            onClick={() => {
              handleLoader("/projects");
            }}
          >
            <h2>Experience&rarr;</h2>
            <p>A rundown of my professional experience</p>
          </div>

          <div
            className={styles.card}
            onClick={() => {
              handleLoader("/other");
            }}
          >
            <h2>Other&rarr;</h2>
            <p>A list of for-fun projects created on this website</p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default HomePage;
